version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
      - "9094"
    environment:
      PORT_COMMAND: "docker port $$(hostname) 9094/tcp | cut -d: -f2"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://10.10.1.5:_{PORT_COMMAND}
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sa:3:1,batch_events:3:1,alerts:2:1,"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
